// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Persistence.Context;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519105853_ChangeUserIdGuid")]
    partial class ChangeUserIdGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Domain.Models.User.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("9de747b6-2026-49b4-b83a-b9fa4b2ac70e"),
                            Email = "test1@test.se",
                            Password = "test1",
                            Username = "test1"
                        },
                        new
                        {
                            UserId = new Guid("e7838127-7522-4684-885b-3d5f89e0f449"),
                            Email = "test2@test.se",
                            Password = "test2",
                            Username = "test2"
                        },
                        new
                        {
                            UserId = new Guid("a9bb2ecc-e45f-451e-bb76-3937f43c66dc"),
                            Email = "test3@test.se",
                            Password = "test3",
                            Username = "test3"
                        },
                        new
                        {
                            UserId = new Guid("b6079694-8b16-40f7-8489-c2245c5c5cc4"),
                            Email = "test4@test.se",
                            Password = "test4",
                            Username = "test4"
                        },
                        new
                        {
                            UserId = new Guid("2cbf1e38-94e5-4d86-a19a-ecaa65936a0e"),
                            Email = "test5@test.se",
                            Password = "test5",
                            Username = "test5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
